INSERT INTO USUARIO(nome, email, senha) VALUES('Aluno', 'aluno@email.com', '$2a$10$1jvZ6dIgt4nXAT9qxEXvUOeyduXL0.DA.u8aRCjW04z5wKYexKFy2');

INSERT INTO CURSO(nome, categoria) VALUES('Spring Boot', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('HTML 5', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Java Fundamentos', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 1', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 2', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 3', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 4', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 5', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 6', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 7', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 8', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 9', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 10', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 11', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 12', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 13', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 14', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 15', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 16', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 17', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 18', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 19', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 20', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 21', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 22', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 23', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 24', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 25', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 26', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 27', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 28', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 29', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 30', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 31', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 32', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 33', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 34', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 35', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 36', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 37', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 38', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 39', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 40', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 41', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 42', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 43', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 44', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 45', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 46', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 47', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 48', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 49', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 50', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 51', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 52', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 53', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 54', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 55', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 56', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 57', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 58', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 59', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 60', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 61', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 62', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 63', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 64', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 65', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 66', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 67', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 68', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 69', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 70', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 71', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 72', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 73', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 74', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 75', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 76', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 77', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 78', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 79', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 80', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 81', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 82', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 83', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 84', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 85', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 86', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 87', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 88', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 89', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 90', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 91', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 92', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 93', 'Front-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Back-end 94', 'Back-end');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Data Science 95', 'Data Science');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de DevOps 96', 'DevOps');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Mobile 97', 'Mobile');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de UI/UX 98', 'UI/UX');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Programação 99', 'Programação');
INSERT INTO CURSO(nome, categoria) VALUES('Curso de Front-end 100', 'Front-end');


INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida', 'Erro ao criar projeto', '2019-10-05 18:00:00', 'NAO_RESPONDIDO', 1, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 2', 'Projeto não compila', '2019-04-05 19:00:00', 'NAO_RESPONDIDO', 1, 1);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 3', 'Tag HTML', '2019-01-05 20:00:00', 'NAO_RESPONDIDO', 1, 2);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 1 sobre Curso 3', 'Mensagem da dúvida 1 para o curso 3.', '2024-05-25 10:04:01', 'NAO_RESPONDIDO', 1, 3);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 2 sobre Curso 3', 'Mensagem da dúvida 2 para o curso 3.', '2024-08-25 10:04:02', 'NAO_RESPONDIDO', 1, 3);
INSERT INTO TOPICO(titulo, mensagem, data_criacao, status, autor_id, curso_id) VALUES('Dúvida 3 sobre Curso 3', 'Mensagem da dúvida 3 para o curso 3.', '2024-10-25 10:04:03', 'NAO_RESPONDIDO', 1, 3);
